apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          env:
            - name: DATABASE_URL
              value: {{ ternary (printf "postgresql+psycopg://%s:%s@postgres:5432/%s" .Values.postgres.username .Values.postgres.password .Values.postgres.database) .Values.postgres.url .Values.postgres.enabled | quote }}
            - name: REDIS_URL
              value: {{ ternary (printf "redis://:%s@redis:6379/0" .Values.redis.password) .Values.redis.url .Values.redis.enabled | quote }}
            - name: LOG_LEVEL
              value: "{{ .Values.backend.logLevel }}"
          resources:
            requests:
              cpu: "{{ .Values.backend.resources.requests.cpu }}"
              memory: "{{ .Values.backend.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
              memory: "{{ .Values.backend.resources.limits.memory }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: backend
