"""New migration

Revision ID: 04456178c03b
Revises: e8df39d7f04b
Create Date: 2025-04-08 18:25:59.649549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '04456178c03b'
down_revision = 'e8df39d7f04b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('spec', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'spec')
    # ### end Alembic commands ###
