"""New migration

Revision ID: 5aca8226e81d
Revises: 04456178c03b
Create Date: 2025-04-08 19:15:10.304029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5aca8226e81d'
down_revision = '04456178c03b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemas', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_schemas_status'), 'schemas', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schemas_status'), table_name='schemas')
    op.drop_column('schemas', 'status')
    # ### end Alembic commands ###
