"""New migration

Revision ID: 955730c1feec
Revises: 5aca8226e81d
Create Date: 2025-04-08 19:22:54.233565

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '955730c1feec'
down_revision = '5aca8226e81d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'parameters_hash')
    op.drop_column('endpoints', 'response_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('response_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('parameters_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
