"""New migration

Revision ID: e8df39d7f04b
Revises: a0cf29e0d972
Create Date: 2025-04-08 14:09:16.299062

"""


# revision identifiers, used by Alembic.
revision = "e8df39d7f04b"
down_revision = "a0cf29e0d972"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
